language: node_js
node_js:
- 13.12.0
cache: yarn
install: yarn install
script:
- yarn build
before_deploy:
- openssl aes-256-cbc -K $encrypted_51bbf948f823_key -iv $encrypted_51bbf948f823_iv -in .deploy/deployer_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- ssh-keyscan -t ecdsa -H $DEPLOY_HOST 2>&1 | tee -a $HOME/.ssh/known_hosts
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -zr --delete --quiet public/ $DEPLOY_PATH
  on:
    branch: master
