language: node_js
node_js:
  - "13.12.0"
cache: yarn
before_install:
  - sed -i 's/registry.npm.taobao.org/registry.yarnpkg.com/g' yarn.lock
install: yarn install
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: telework-club/telework-club.github.io
  local_dir: public
  target_branch: master
  keep_history: true
  on:
    branch: master
