language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "13.12.0"
deploy:
  provider: script
  script: sed -i 's/registry.npm.taobao.org/registry.yarnpkg.com/g' yarn.lock && yarn install && yarn deploy
  skip_cleanup: true
  on:
    branch: master
